version: '3.8'
services:
  backend:
    image: ${DOCKERHUB_USERNAME}/pharma-backend:latest
    container_name: pharma-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - pharmanet

  frontend:
    image: ${DOCKERHUB_USERNAME}/pharma-frontend:latest
    container_name: pharma-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pharmanet

networks:
  pharmanet:
    driver: bridge
