version: '3.8'
services:
  backend:
    build: ./backend
    container_name: pharma-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - pharmanet

  frontend:
    build: ./frontend
    container_name: pharma-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - pharmanet

networks:
  pharmanet:
    driver: bridge
