version: '3.8'
services:
  backend:
    build: ./backend
    container_name: pharma-backend
    ports:
      - "3000:3000"
    depends_on:
      - fabric
    environment:
      - NODE_ENV=production
    networks:
      - pharmanet

  frontend:
    build: ./frontend
    container_name: pharma-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - pharmanet

  fabric:
    image: hyperledger/fabric-peer:2.5
    container_name: fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
    volumes:
      - /var/run/:/host/var/run/
    networks:
      - pharmanet
    # Note: In a real setup, you would define all Fabric services (orderer, ca, couchdb, etc.)
    # and use the official fabric-samples/test-network scripts or images.

networks:
  pharmanet:
    driver: bridge

